
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-deployment
  labels:
    component: grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: grpc-server
  template:
    metadata:
      labels:
        component: grpc-server
    spec:
      containers:
        - name: container
          envFrom:
          # - configMapRef:
          #     name: rds-dbs-config-map
          # - secretRef:
          #     name: rds-creds-secret
          - configMapRef:
              name: grpc-configmap
          args: ["--grpc_port=$(METADATA_GRPC_SERVICE_PORT)",
                 "--mysql_config_host=$(host)",
                 "--mysql_config_database=$(DATABASE)",
                 "--mysql_config_port=$(port)",
                 "--mysql_config_user=$(username)",
                 "--mysql_config_password=$(password)"
          ]
