apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
bases:
- ../../env/platform-agnostic
configMapGenerator:
- name: pipeline-install-config
  envs: ["params.env"]
  behavior: merge
- name: workflow-controller-configmap
  behavior: replace
  files:
  - config
- name: ml-pipeline-ui-configmap
  behavior: replace
  files:
  - viewer-pod-template.json
secretGenerator:
- name: mlpipeline-minio-artifact
  envs: ["minio-artifact-secret-patch.env"]
  behavior: merge
generatorOptions:
  disableNameSuffixHash: true
patchesStrategicMerge:
- aws-configuration-patch.yaml
commonLabels:
  application-crd-id: kubeflow-pipelines
