apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-api-server
        envFrom:
        - configMapRef:
            name: pipeline-api-server-config
        env:
        - name: KUBEFLOW_USERID_HEADER
          valueFrom:
            configMapKeyRef:
              name: kubeflow-config
              key: userid-header
        - name: KUBEFLOW_USERID_PREFIX
          valueFrom:
            configMapKeyRef:
              name: kubeflow-config
              key: userid-prefix
        - name: OBJECTSTORECONFIG_SECURE
          value: "true"
        - name: OBJECTSTORECONFIG_BUCKETNAME
          valueFrom:
            configMapKeyRef:
              name: pipeline-install-config
              key: bucketName
        - name: OBJECTSTORECONFIG_HOST
          valueFrom:
            configMapKeyRef:
              name: pipeline-install-config
              key: minioServiceHost
        - name: OBJECTSTORECONFIG_REGION
          valueFrom:
            configMapKeyRef:
              name: pipeline-install-config
              key: minioServiceRegion
        - name: OBJECTSTORECONFIG_PORT
          value: ""

