#TODO this must also be mirrored!

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
  annotations: {
    "reflector.v1.k8s.emberstack.com/reflects": "default/knative-config-domain" #this configmap will be reflected from "default/rds-dbs-config-map"  which is NOT defined in these manifests and not created by kfctl.
  }
---
apiVersion: v1
data: 
  domainTemplate: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
kind: ConfigMap
metadata:
  labels:
    serving.knative.dev/release: v0.14.3
  name: config-network
  namespace: knative-serving